import {
  LayoutGrid,
  Mail,
  FileText,
  Users,
  Package,
  FolderTree,
  ListChecks,
  Award,
  Image as ImageIcon,
  FolderOpen,
  File,
  PenLine,
  HelpCircle,
  BookOpen,
  Menu,
  Settings,
  BarChart3,
  ShieldCheck,
  MailCheck,
  Percent,
  CreditCard,
  Link2,
  Terminal,
  ArrowRightLeft,
  UserCircle,
  ShieldQuestion,
  History,
  Activity,
  type LucideIcon,
} from 'lucide-react'

export const navIconMap: Record<string, LucideIcon> = {
  '/admin/dashboard': LayoutGrid,
  '/admin/enquiries': Mail,
  '/admin/form-submissions': FileText,
  '/admin/newsletter': MailCheck,
  '/admin/products': Package,
  '/admin/categories': FolderTree,
  '/admin/attributes': ListChecks,
  '/admin/brands': Award,
  '/admin/homepage-banner': ImageIcon,
  '/admin/media': FolderOpen,
  '/admin/pages': File,
  '/admin/blog-posts': PenLine,
  '/admin/faqs': HelpCircle,
  '/admin/catalogue': BookOpen,
  '/admin/menus': Menu,
  '/admin/settings/site': Settings,
  '/admin/settings/analytics': BarChart3,
  '/admin/settings/spam': ShieldCheck,
  '/admin/settings/smtp': Mail,
  '/admin/settings/tax': Percent,
  '/admin/settings/payments': CreditCard,
  '/admin/settings/webhooks': Link2,
  '/admin/settings/technical': Terminal,
  '/admin/settings/redirects': ArrowRightLeft,
  '/admin/customers': Users,
  '/admin/users': UserCircle,
  '/admin/roles': ShieldQuestion,
  '/admin/audit-log': History,
  '/admin/health': Activity,
}
